[project]
name = "duckdb-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.9.2,<2.0.0",
    "dbt-duckdb>=1.9.2,<2.0.0",
    "duckdb>=1.2.0",
    "pytest>=8.3.4",
]
